id: P006998
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W28979
  title: རྟ་ནག་རྣམ་འགྲེལ
  author: ''
  volumes:
    eb1bb035fc384c4a886b19bf9e509c4e:
      image_group_id: I5709
      title: ''
      volume_number: 1
      total_pages: 929
      base_file: v001.txt
